#!/bin/bash
CONDA_ENVNAME='pcds-0.5.2'
CONDA_BASE='/reg/g/pcds/pyps/conda/py36'

HERE=`readlink -f $(dirname $0)`

export PYTHONPATH="${HERE}:${HERE}/dev/devpath"
export LD_LIBRARY_PATH=''

CONDA_ENV="${CONDA_BASE}/envs/${CONDA_ENVNAME}"
CONDA_BIN="${CONDA_ENV}/bin/wrappers/conda"

source /reg/g/pcds/setup/pathmunge.sh
pathmunge "${CONDA_BIN}"
hutch-python --cfg "${HERE}/conf.yml" --db "${HERE}/../device_config/db.json" $@
