#!/bin/bash
CONDA_ENV='pcds-0.5.0'
CONDA_BASE='/reg/g/pcds/pyps/conda/py36'

export PYTHONPATH=''
export LD_LIBRARY_PATH=''

source /reg/g/pcds/setup/pathmunge.sh
pathmunge "${CONDA_BASE}/envs/${CONDA_ENV}/bin/wrappers/conda"

pushd `readlink -f $(dirname $0)`
hutch-python conf.yml
popd
